### ISSUE TITLE
HUD

### ISSUE THREAD

**Issue by Tkocz** [philiparvidsson/Sap6-Game#101]
for life, inventory & berserkmode

**Comment by philiparvidsson** [comment]
see #110 for hud (it's a separate card because it only deals with the engine part of it, while this card seems to deal with the game-specific part of the hud)

**Comment by philiparvidsson** [comment]
https://github.com/philiparvidsson/Sap6-Game/commit/27f50ca0dcb88afdaa13d9963fc4d9107dac7be7

(I'm not taking this—only providing a starting point for the card.)

**Comment by tobiasanhed** [comment]
Scoresystem, number of killed sheeps and other animals
