### ISSUE TITLE
Model origo is located in boundingbox origo

### ISSUE THREAD

**Issue by crippa9** [philiparvidsson/Sap6-Game#108]

**Comment by philiparvidsson** [comment]
not sure in what manner this is an issue so making a discussion out of it.

does this need to be changed? if I recall correctly, it's the world vs bound (or map) test that uses the width/height/depth of the bounding box to compute the corner vertices, so the origin gets "recentered" to the transform position on each test.

fairly easy to fix if it is indeed an issue.

**Comment by crippa9** [comment]
It's a design decision, but if we are to have models centered at origo, all models need to do so. Right now some are and some aren't
