### ISSUE TITLE
AssemblyInfo.cs is per-project and should be in the source folder (or removed)

### ISSUE THREAD

**Issue by philiparvidsson** [philiparvidsson/Sap6-Game#5]
if the AssemblyInfo.cs file is not *required* to compile the project—remove it. if it is, place one AssemblyInfo.cs in each of the assembly source directories

**Comment by tobohr** [comment]
AssemblyInfo.cs contains information about your assembly, like name, description, version, ecc. You can find more details about its content reading the comments that are included in it.

If you delete it, your assembly will be compiled with no information, i.e., in the Details tab of the file properties you will see no name, no description, version 0.0.0.0, etc.

The value associated with assembly:Guid is the ID that will identify the assembly if it will be exposed as a COM object. So, if your assembly isn't COM-exposed, you don't need this. It is randomly generate. In any case, normally, you don't need to modify it.
