### ISSUE TITLE
convert fps counter to use an overlay display

### ISSUE THREAD

**Issue by philiparvidsson** [philiparvidsson/Sap6-Game#61]
now that there is 2d text drawing functionality, using the window title is pretty ugly, better to use an overlay. 

optionally, extend scope of this issue to include further debug info in the overlay (and rewrite the entire fps counter system into a new class), such as number of entities etc.

**Comment by philiparvidsson** [comment]
not sure if wip but fps info is not showing up at all?

**Comment by Tkocz** [comment]
merely pointless in menu: applied in worldscene

**Comment by philiparvidsson** [comment]
https://github.com/philiparvidsson/Sap6-Game/commit/6268d8523744a39c99a25e6f57285f1eb639ce72

**Comment by philiparvidsson** [comment]
code review looks good
