### ISSUE TITLE
network functionality

### ISSUE THREAD

**Issue by philiparvidsson** [philiparvidsson/Sap6-Game#64]
as this will be an ongoing work, the scope of this card is to implement network connectivity, for the sake of simplicity (and the fact that there likely will never be many players) a peer-to-peer network topology is probably preferable. no functionality beyond the connection is within the scope of this card.

**Comment by tobohr** [comment]
https://github.com/philiparvidsson/Sap6-Game/commit/a66918516c67e01d1577e820e67ea7e9fb00f5f6
