### ISSUE TITLE
Should we really have a system for water and maps?

### ISSUE THREAD

**Issue by crippa9** [philiparvidsson/Sap6-Game#85]
They neither update nor draw, so could just as well be turned into other types of classes?

**Comment by philiparvidsson** [comment]
Correct, water and maps should not be systems. It would make more sense for a system to derive from RenderingSystem. Implemented in the GameName project, it would contain the water and map data (which is a fairly game-specific concept).

**Comment by crippa9** [comment]
Although physics system is dependent of a function from map system right now to know heights of the map, so this has to be handled

**Comment by philiparvidsson** [comment]
This issue ties into #95 so I'm taking on both.
